---
abstract: 'Perl interface for Apache response variables'
author:
  - 'Dmitry Kosenkov & <d.kosenkov@rambler-co.ru>'
build_requires:
  ExtUtils::PkgConfig: 1.03
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dendral-HTTP-Response
no_index:
  directory:
    - t
    - inc
requires: {}
version: v0.1.0
